### ISSUE TITLE
В редких случаях чат ломается

### ISSUE THREAD

**Issue by Lizurt** [Pl3aseJust3ndMySuffering/RUTGMC#7]
## Testmerges:

Нет?

## Reproduction:

Не знаю как точно повторить этот баг, но иногда, при осмотре чего-нибудь через шифт клик, чат ломается. Ну, во первых, никакого осмотра не происходит. А во вторых чат умирает, новые сообщения там не появляются, хотя игра идет нормально. В чат выводится также сообщение о проблемах соединения

С проблемой сталкивался не только я. Бинды и макросы скорее всего не виноваты:

LOOC: Aria 'Toxic' Lemon: он вроде случайно сам ломается
LOOC: Aria 'Toxic' Lemon: у меня такая же проблема, только на шифт биндов нет

Возможно вообще не связано с Examine. Мне удалось сломать его 2 раза через Examine и 1 раз он сломался просто так.

Также ломаются звуки - их не слышно

**Comment by Lizurt** [comment]
Держу в курсе, но возможно дело не в Examine. Похоже он так же не прочь сломаться и просто так

**Comment by Pl3aseJust3ndMySuffering** [comment]
> Держу в курсе, но возможно дело не в Examine. Похоже он так же не прочь сломаться и просто так

Оказывается, проблема в базе данных и том, как она решает проблему большого количества одновременных запросов. Мне удалось уменьшить количество вылетов, увеличив параметр. Сегодня на запуске посмотрим.

**Comment by Pl3aseJust3ndMySuffering** [comment]
Пофикшено...
